### PR TITLE
Fix new_tag_prefix on new entities when re submit

### PR DESCRIPTION
**Pull request by Seb33300**
Fix for https://github.com/tetranz/select2entity-bundle/issues/75

### CODE REVIEW

**Comment by tetranz** [comment]
Thanks. I had a play with this today but unfortunately it doesn't work.

Firstly I think the line:
`$data = is_array($form->getData()) ? $form->getData() : [$form->getData()];`
needs to be something more like this:
`$data = $options['multiple'] ? $form->getData() : [$form->getData()];`
Then $data will always be an iterable collection or array of one or more entities.

That almost works except that it has a problem with a multiple select where more than one new entity has been added with tags. I didn't quite solve that and can't spend any more time on it now. Maybe I'll take another look next weekend if nobody else wants to debug this.

**Comment by Seb33300** [comment]
I have updated to use `$options['multiple']`.
It was working when I tested it with multiple new entities. If I have the time, will try to make others tests this week to find what could be wrong.

**Comment by Seb33300** [comment]
Hi, I just made multiple tests and it worked in every cases on multiple select.
I tested with multiple new tags, and mixed existing and new tags... all worked fine.

**Comment by Seb33300** [comment]
I just added the fix for the `new_tag_prefix`.

**Comment by tetranz** [comment]
Unfortunately this still didn't work for me. The main issue is that when displaying again after the failed post,  `$view->vars['value']` does not contain keys for the newly created items. It contains one item with a blank string for a key regardless of how many new items were added.

I've done my own fix for this. I think this works. Could you give it a test please @Seb33300. I'd like you or someone to try it before I merge. Thanks.

https://github.com/tetranz/select2entity-bundle/tree/tag-submit-fix

**Comment by Seb33300** [comment]
I don't understand what `$view->vars['value']` contains in your case?
Only one value ? `array('' => ???)`

I will only able to test your code until next Tuesday.
But in my case, the `$view->vars['value']` array, doesn't contains a blank key.
So I think `unset($view->vars['value']['']);` should be replaced by `$view->vars['value'] = array();`

**Comment by tetranz** [comment]
I have a multiple value select which already has one value. id = 176, value  = Vasquez. If I add a new value (aaa) with a tag, `$view->vars['value']` looks like this in finishView.


The key for that second element is a blank string. If I add two new items, aaa and bbb, it ends up like this:


I guess they both have a key of blank string so the second overwrites the first.

My new code gets rid of that bad item and uses the newly created (but not yet saved) entities to rebuild `$view->vars['value']` as this:


My prefix is __.

Even if there are no existing items, `$view->vars['value']` is still an array with just that weird item so it will be an empty array after the unset.

I don't know why you are I are seeing different things. I have a pretty standard form, nothing unusual.

**Comment by Seb33300** [comment]
I understand why you have a blank value and why I don't.

This is because your entities are not persisted and `getId()` will return null on new entities.

But in my case, I have set `primary_key` and `text_property` options to another field on my product entity (`sku` field) because I would like to get the `sku` as the value on my select.
So select2Entity is able to create new entities and fill the `sku` field, so the value is not blank.

When using `primary_key` and `text_property` to use the same entity filed, this will result in:

Before your fix
```php
array(
    'SKUXXXX' => 'SKUXXXX',
    'aaa' => 'aaa',
    'bbb' => 'bbb'
}
```

After your fix
```php
array(
    'SKUXXXX' => 'SKUXXXX',
    'aaa' => 'aaa',
    'bbb' => 'bbb',
    '_aaa' => 'aaa',
    '_bbb' => 'bbb'
}
```

Because you only unset the blank key.
So you should do `$view->vars['value'] = array();` instead of `unset($view->vars['value']['']);`;

**Comment by tetranz** [comment]
Ok, thanks. That explains the difference. I don't touch my new entities until just before I flush in the controller. My primary key is an auto number from the database. You have a primary key for the new entities in finishView but I don't. I guess we need to make it work for both situations.

I've updated my PR. I think that will work for both. Let me know what you think.

**Comment by tetranz** [comment]
I'm going out now but I think that's not quite right. We still need to add the prefix for your entities that have a primary key but are not in $this->em->contains. I'll take another look later today.

**Comment by Seb33300** [comment]
I don't understand why you add prefix only if `$primaryKey` is null.
In my case, the `$primaryKey` is not null (because I set the same value in `primary_key` and `text_property` options), but it is a new entity so I need the prefix.

This should be:
```
if (!$this->em->contains($entity)) {
    $primaryKey = $newTagPrefix . $text;
}
```

In my case, the `sku` field is not the primary key of my entity (but it has a unique constraint).
It's just the value I want to post with the form.

I don't know why this option is called `primary_key`. This should be called `choice_value` linke in the Symfony `EntityType` (http://symfony.com/doc/current/reference/forms/types/entity.html#choice-value).
And `text_property` options should be called `choice_label` as well (http://symfony.com/doc/current/reference/forms/types/entity.html#choice-label).

**Comment by Seb33300** [comment]
(just edited my post)

You are right in your last comment.
I also add comments on your pull request.

**Comment by tetranz** [comment]
I've updated again. I think it should be better now.

I agree about the option names. Maybe when this is done I'll change the names. Of course I'll keep the old ones working too to avoid breaking anything.

ALSO OFF TOPIC
I'm not sure what that `full_name` stuff is about below the area we're looking at. That surely doesn't look right. I'll investigate that.

**Comment by tetranz** [comment]
Fixed by https://github.com/tetranz/select2entity-bundle/pull/80

**Pull request closed without merging**
