### PR TITLE
Allow tags support, enables you to create new entities.

### PR DESCRIPTION
**Pull request by Emirii**
3 new options have been created to allow adding new tags with Select2 if
the searched tag does not exist:

allow_add - enables the Select2 tags: true
allow_add_text - the text displayed next to a tag that has been created.
Default text is " (NEW)"
allow_add_separator - A javascript array with the delimiters that will
create new tags.

There is a small bug with cache and allow_add enabled, and I am not sure whether it is directly Select2 issue or not. It's not really game breaking though, but maybe someone has a clue. Reproduce:
1. Enable cache true
2. Enable allow_add true
3. In Select2 box, type non-existing tag "Hello"
4. Select the "Hello (NEW)" in drop down to select it as a tag
5. Type again "Hello" in the box, now 2 "Hello (NEW)" appear in the select menu. IF you click it won't add it a second time, which is correct behavior. 
6. Type "Hello" again, now there are 3 and so on.

I tried debugging it but I could not find out where this was coming from. Confirmed my ajax results were [], the key was in cache, but not displaying more than once in cache. 

Thank you for the awesome bundle!

### CODE REVIEW

**Comment by tetranz** [comment]
Thanks. I tried this and it looks good but, unless I'm missing something, it has a couple of problems.

In the reverseTransform code the query fails because newly created string ids are an invalid type which makes Doctrine throw a DriverException which we catch and rethrow. I don't see how it worked for you.

It seems to me that we need to filter the values to only give the query non-new ids.

I think there's also an issue that we don't insist in numeric ids so testing for ctype_digit is not necessarily a solid way to determine which ids are new. I don't know if there is an easy solution to that. If not, I'm okay with just adding a note to say that you must use numeric ids if you want to use tagging. The only other way I can think of is to somehow add a unique prefix to the new ids. Something like, if an id starts with an underscore then it must be a new id. That prefix probably needs to be a config setting.

**Comment by Emirii** [comment]
> I don't see how it worked for you.
I don't know how either, now that I really think about it. Perhaps my DB setup is more lax. I will look into that.

Thanks for the feedback, I will continue to refine. I was trying to make it as little code as possible, but I might have to do some comparisons between existing and new additions with tagging.

Your idea with the _ prefix (or other) would probably be a better idea rather than relying on the "id" being an INT.

Ill see what I can do, thanks for the feeback!

**Comment by Emirii** [comment]
I have pushed a new commit, check it out. I think it solves all of your concerns, but if you think of any better suggestion let me know and I'll implement it!

**Comment by tetranz** [comment]
Merged, thanks.  Looks good.

I see what you mean about the caching issue. I'll see if I can figure out what's happening there.

I've let this settle for a few days and then tag a new release.

**Pull request merged**
