### PR TITLE
Custom transformer functionality

### PR DESCRIPTION
**Pull request by tmisheva**
- Adding custom transformer functionality allowing to have custom text that can display more than one entity property. 

- Adding support for custom templates for the option text, which allows for adding option images.

- Updated README with the new additions.

### CODE REVIEW

**Comment by tetranz** [comment]
Thanks. I only had a quick look but it looks really good.

I'll study it more when I get time in the next few days and probably merge.

**Comment by tmisheva** [comment]
Thanks, let me know if you have any remarks.

**Comment by tetranz** [comment]
Merged.

My only thought was that perhaps it would be better to validate that the custom transformer implements DataTransformerInterface rather than insist that it extends the default transformer. I guess it doesn't make much difference.

**Comment by tmisheva** [comment]
Sorry for the late reply.  

Yes, maybe you're right. I was wondering about checking the interface only, as it would be more flexible for the users.
On the other hand, when extending `EntitiesToPropertyTransformer`/`EntityToPropertyTransformer` they extend all other functionality (__construct, reverseTransform) that could potentially change in the bundle.

Maybe we should check only for `instanceof DataTransformerInterface` but in the README to recommend extending `EntitiesToPropertyTransformer`/`EntityToPropertyTransformer` class.

Would you like me to do this change?

**Comment by tetranz** [comment]
Your suggestion sounds good with the interfaces and a recommendation to extend the default classes. If you want to do that change, I'm merge it, no problem, and then tag a new release.

Thanks

**Comment by tmisheva** [comment]
It's a minor change - just the `Form/Type/Select2EntityType.php:76` should change to:
```
if (!$transformer instanceof DataTransformerInterface) {
    throw new \Exception(sprintf('The custom transformer %s must implement %s', get_class($transformer), DataTransformerInterface::class));
}
```
However I won't be able to test it properly and do a pull request in the next couple of weeks. Unless you want to do it now, I'll do it when I can.

**Comment by tetranz** [comment]
Thanks. I just did it, updated the documentation and released version 2.4.

**Pull request merged**
