### PR TITLE
Support to select2 ajax

### PR DESCRIPTION
**Pull request by morra850**
fix error 

> `option 'ajax' is not allowed for Select2 when attached to a <select> element`

### CODE REVIEW

**Comment by tetranz** [comment]
Sorry, I don't understand this.

This shows ajax being used with a <select>  https://select2.org/data-sources/ajax

**Comment by tetranz** [comment]
I think is this an issue for versions of Select2 before version 4.

Thanks but I don't think I want to merge this. All the examples for Select2 v4 use <select>. I think we might have to accept that we only support Select2 v4 moving forward.

https://select2.org/getting-started/basic-usage

**Comment by DubbleClick** [comment]
This should definitely not be merged. It wouldn't only add compatibility issues, but even remove functionality.

**Comment by DubbleClick** [comment]
I'm all for closing this. If anyone really needs to support select <4.0, they will simply have to extend the .select2entity() function themselves.

**Pull request closed without merging**
